#-------------------#
#   itkTensorFlow   #
#-------------------#

os:
  - Visual Studio 2017

init:
  - git config --global core.autocrlf input
  # Set build version to git commit-hash
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

environment:
  ZIP_EXTENDED_NAME: itkTensorFlow_%APPVEYOR_REPO_TAG_NAME%_windows_%PLATFORM%

install:
  - git submodule update --init --recursive

platform:
  - Win32
  - x64

configuration:
  - Release

before_build:
  - echo %PLATFORM%
  - echo %configuration%
  - dir
  - cd
  - cd ..
  - cd
  - curl -L -O https://www.dropbox.com/s/fu5we0o2j1a4uzt/ITK412_win_%PLATFORM%_install.zip
  - dir
  - cd
  - 7z x -r ITK412_win_%PLATFORM%_install.zip
  - dir
  - cd itkTensorFlow
  - cd
  - dir
  - cmake . -Bbin -A%PLATFORM% -DCMAKE_INSTALL_PREFIX=install -DITK_DIR_HINTS="../ITK_install"
  - cd
  - dir bin
  - if [%PLATFORM%]==[Win32] (
      cd thirdpart/tensorflow/bin
      lib /def:yourpath/tensorflow.def /OUT:yourpath/tensorflow.lib /MACHINE:X86
      cd ../../..
  )

build:
  project: bin\itkTensorFlow.sln  # path to Visual Studio solution or project
  parallel: true           # enable MSBuild parallel builds
  verbosity: normal        # MSBuild verbosity level {quiet|minimal|normal|detailed}

after_build:
  # install the files
  - cd bin
  - dir
  # - cmake --build . --config %CONFIGURATION% --target ALL_BUILD
  - cmake --build . --config %CONFIGURATION% --target INSTALL
  - dir %CONFIGURATION%
  - cd ..
  - dir install
  - cd install
  - 7z a %ZIP_EXTENDED_NAME%.zip * -r # zip
  - cd ..
  - mkdir deployment
  - copy install\%ZIP_EXTENDED_NAME%.zip deployment\%ZIP_EXTENDED_NAME%.zip
  - dir
  - dir deployment

test_script:
  # TODO: should I add sth like this? https://github.com/mgerhardy/caveexpress/blob/master/appveyor.yml
  - cd
  - dir
  - cd bin\tests\%CONFIGURATION%
  - itkTensorFlowTests.exe
  - cd ..\..\..

artifacts:
  - path: deployment\*.*

deploy:
  provider: GitHub
  auth_token:
    secure: Nmbbo4JCoK5AuN1ugWmE/c8/BAXlpz8Lb7piWDcAAWnT/GFa7fwL20GbXyU9AZSn
  draft: false
  prerelease: false
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
    configuration: Release
