#-------------------#
#   itkTensorFlow   #
#-------------------#

os:
  - Visual Studio 2017

init:
  - git config --global core.autocrlf input
  # Set build version to git commit-hash
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

environment:
  toolset: v140
  EXE_EXTENDED_NAME: itkTensorFlowExe_%APPVEYOR_REPO_TAG_NAME%_windows_%PLATFORM%
  LIB_EXTENDED_NAME: itkTensorFlowLib_%APPVEYOR_REPO_TAG_NAME%_windows_%PLATFORM%

install:
  - git submodule update --init --recursive

platform:
#  - Win32
  - x64

configuration:
  - Release

before_build:
  - echo %platform%
  - echo %configuration%
  - cd %APPVEYOR_BUILD_FOLDER%\..
  - mkdir ITK_install
  - cd ITK_install
  - curl -L https://github.com/MRKonrad/build-itk/releases/download/itk_v4.13.2/itk_v4.13.2_windows_%PLATFORM%_%toolset%.zip -o itk_install.zip
  - 7z x -r itk_install.zip
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmake . -Bbin -A%PLATFORM% -T%toolset% -DCMAKE_INSTALL_PREFIX=install -DITK_DIR_HINTS="../ITK_install"

build:
  project: bin\itkTensorFlow.sln  # path to Visual Studio solution or project
  parallel: true           # enable MSBuild parallel builds
  verbosity: normal        # MSBuild verbosity level {quiet|minimal|normal|detailed}

after_build:
  # install the files
  - cd %APPVEYOR_BUILD_FOLDER%\bin
  - dir
  # - cmake --build . --config %CONFIGURATION% --target ALL_BUILD
  - cmake --build . --config %CONFIGURATION% --target INSTALL
  - dir %CONFIGURATION%
  - dir %APPVEYOR_BUILD_FOLDER%\bin\install
  - dir %APPVEYOR_BUILD_FOLDER%\bin\install\bin
  - dir %APPVEYOR_BUILD_FOLDER%\bin\install\lib
  - dir %APPVEYOR_BUILD_FOLDER%\bin\install\include

  - cd %APPVEYOR_BUILD_FOLDER%\bin\install\bin
  - 7z a %EXE_EXTENDED_NAME%.zip * -r # zip
  - cd %APPVEYOR_BUILD_FOLDER%\bin\install
  - 7z a %LIB_EXTENDED_NAME%.zip lib include -r # zip

  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir deployment

  - copy %APPVEYOR_BUILD_FOLDER%\bin\install\bin\%EXE_EXTENDED_NAME%.zip %APPVEYOR_BUILD_FOLDER%\deployment\%EXE_EXTENDED_NAME%.zip
  - copy %APPVEYOR_BUILD_FOLDER%\bin\install\%LIB_EXTENDED_NAME%.zip %APPVEYOR_BUILD_FOLDER%\deployment\%LIB_EXTENDED_NAME%.zip
  - dir deployment

test_script:
  # TODO: should I add sth like this? https://github.com/mgerhardy/caveexpress/blob/master/appveyor.yml
  - cd %APPVEYOR_BUILD_FOLDER%\bin\tests\%CONFIGURATION%
  - itkTensorFlowTests.exe

artifacts:
  - path: deployment\*.*

deploy:
  provider: GitHub
  auth_token:
    secure: Nmbbo4JCoK5AuN1ugWmE/c8/BAXlpz8Lb7piWDcAAWnT/GFa7fwL20GbXyU9AZSn
  draft: false
  prerelease: false
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
    configuration: Release
