language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
    - exe_extended_name: itkTensorFlowExe_${TRAVIS_BRANCH}_${TRAVIS_OS_NAME}
    - lib_extended_name: itkTensorFlowLib_${TRAVIS_BRANCH}_${TRAVIS_OS_NAME}
    - secure: ${GH_PERSONAL_ACCESS_TOKEN}

install:
  # download ITK
  - cd ${TRAVIS_BUILD_DIR}/..
  - curl -L -O http://mrkonrad.github.io/MRKonrad/files/ITK_built/ITK413_${TRAVIS_OS_NAME}_install.zip
  - unzip -a -q ITK413_${TRAVIS_OS_NAME}_install.zip
  - cd ${TRAVIS_BUILD_DIR}/thirdParty/googletest

script:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake . -Bbin -DITK_DIR_HINTS="../ITK_install" -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/bin/install
  - cmake --build bin --config RELEASE --target itkTensorFlowTests
  - cd bin/tests
  - ./itkTensorFlowTests

before_deploy:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake --build bin --config RELEASE --target install
  - ls ${TRAVIS_BUILD_DIR}/bin/install
  - ls ${TRAVIS_BUILD_DIR}/bin/install/bin
  - ls ${TRAVIS_BUILD_DIR}/bin/install/lib
  - ls ${TRAVIS_BUILD_DIR}/bin/install/include

  - cd ${TRAVIS_BUILD_DIR}/bin/install/bin
  - zip -r itkTensorFlowExe.zip *
  - cd ${TRAVIS_BUILD_DIR}/bin/install
  - zip -r itkTensorFlowLib.zip lib include

  - cd ${TRAVIS_BUILD_DIR}
  - mkdir deployment

  - cp ${TRAVIS_BUILD_DIR}/bin/install/bin/itkTensorFlowExe.zip ${TRAVIS_BUILD_DIR}/deployment/${exe_extended_name}.zip
  - cp ${TRAVIS_BUILD_DIR}/bin/install/itkTensorFlowLib.zip ${TRAVIS_BUILD_DIR}/deployment/${lib_extended_name}.zip
  - ls ${TRAVIS_BUILD_DIR}
  - ls ${TRAVIS_BUILD_DIR}/deployment

deploy:
  provider: releases # GitHub
  api_key:
    secure: ${GH_PERSONAL_ACCESS_TOKEN}
  file_glob: ON # to use wildcards
  file: deployment/*
  skip_cleanup: ON
  on:
    tags: ON
    condition: ${CXX} == "clang++" # I guess I have to pick one compiler

notifications:
  slack:
    rooms:
      - secure: xelZIHZuWerzZ9LsGuSQIlNDRmAW2oKjK3tjDGXfJvYmZDTaFua2+OLyYnXelPVpZNKBsG8tuzrAThhvpgY8TbsxLD2wOQ4ZoL7Zf3VqJqkA3HmlUKrZmvDbkoAkd48x81WmeQpusk0Gx4E6mnVi9tcg54HDhWKP4mfQm6/SZQooxl2uiNMjmqu/GwnEtnOl5SD+5+KonyJWbcLwDBOGQFeNwBoc7yGv2FC32Jl51BD9i9AJvEG/hClm3qmUHQrs+wcp4XesrNhaRv2pHmZzsXlMKWgWOd6ngf98ebJiWvtgX2ch1H5B66JviCe2OgBIPLpbBkaR0T7X73wxfgRKH6rPkCXRInOd1K9zWKJprBTlwVyx6ARUWWuOdltIxDbK5aIbn4FD1AKMdEqYve4tChcfwlWTKKAL9Ny1CNl5Udw/69YJWyl+XuJHXAtyE/ba7nrmCKCLrZWG6kKX28+dWrHTMXR4XO9eLOkfz9kLwGiJMkKUm7ClibGANYCxJuNfJL0zwQU/+kUMQ83XdlRXc2TvUo6Fn962Epi61cSbGpbfr5yIgUpkxhvIPIfvTjPg+/qbbNHeqo9nd46jjJP+XQXKK5ZFmrils7y4VGhmGdlPs/axkdDf49Nu/bV9qMCFPA5Q2K5UzdJ5JFw/IWZ0sgM6RtVs0x7np5uYpz6HcBQ=
    on_success: always
