language: cpp

os:
  - linux
  - osx

dist:
  - precise # Ubuntu 12.04

compiler:
  - gcc
  - clang

env:
  global:
    - exe_extended_name: itkTensorFlowExe_${TRAVIS_BRANCH}_${TRAVIS_OS_NAME}
    - lib_extended_name: itkTensorFlowLib_${TRAVIS_BRANCH}_${TRAVIS_OS_NAME}
    - secure: ${GH_PERSONAL_ACCESS_TOKEN}

install:
  # update cmake, necesary for precise
  - sudo apt remove --purge --auto-remove cmake
  - mkdir ~/temp
  - cd ~/temp
  - wget https://cmake.org/files/v3.14/cmake-3.14.3.tar.gz
  - tar -xzvf cmake-3.14.3.tar.gz
  - cd cmake-3.14.3/
  - ./bootstrap
  - make -j4
  - sudo make install
  - cmake --version
  # download ITK
  - cd ${TRAVIS_BUILD_DIR}/..
  - curl -L -O http://mrkonrad.github.io/MRKonrad/files/ITK_built/ITK413_${TRAVIS_OS_NAME}_install.zip
  - unzip -a -q ITK413_${TRAVIS_OS_NAME}_install.zip
  - cd ${TRAVIS_BUILD_DIR}/thirdParty/googletest

script:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake . -Bbin -DITK_DIR_HINTS="../ITK_install" -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/bin/install
  - cmake --build bin --config RELEASE --target itkTensorFlowTests
  - cd bin/tests
  - ./itkTensorFlowTests

before_deploy:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake --build bin --config RELEASE --target install
  - ls ${TRAVIS_BUILD_DIR}/bin/install
  - ls ${TRAVIS_BUILD_DIR}/bin/install/bin
  - ls ${TRAVIS_BUILD_DIR}/bin/install/lib
  - ls ${TRAVIS_BUILD_DIR}/bin/install/include

  - cd ${TRAVIS_BUILD_DIR}/bin/install/bin
  - zip -r itkTensorFlowExe.zip *
  - cd ${TRAVIS_BUILD_DIR}/bin/install
  - zip -r itkTensorFlowLib.zip lib include

  - cd ${TRAVIS_BUILD_DIR}
  - mkdir deployment

  - cp ${TRAVIS_BUILD_DIR}/bin/install/bin/itkTensorFlowExe.zip ${TRAVIS_BUILD_DIR}/deployment/${exe_extended_name}.zip
  - cp ${TRAVIS_BUILD_DIR}/bin/install/itkTensorFlowLib.zip ${TRAVIS_BUILD_DIR}/deployment/${lib_extended_name}.zip
  - ls ${TRAVIS_BUILD_DIR}
  - ls ${TRAVIS_BUILD_DIR}/deployment

deploy:
  provider: releases # GitHub
  api_key:
    secure: ${GH_PERSONAL_ACCESS_TOKEN}
  file_glob: ON # to use wildcards
  file: deployment/*
  skip_cleanup: ON
  on:
    tags: ON
    condition: ${CXX} == "clang++" # I guess I have to pick one compiler

notifications:
  slack:
    rooms:
      - secure: "Bw8AaTA6bKabgubrEmlkIvoyZ86GMWspUvkLumUuOJfGX3DEo8DYxmi/XdE3CTYsgDSOPH1CAhX/YHqmi7FRNYQsHv2++RPGJ3xbhY0A6KZ1j/69BZ3GC97P6yjVZbv7x0NXWFfxEJCkTA21fVssdLIDwpL7wdGaDSnf2219khP9jNbvrFlxZKxhAI9qiLBcQebJ1tHNW9MDmvMHxmL4m2wKEzebbRGZdEUOEivCsw8k4S+CxH4ThseEANuN8uhM46CNs7wFz03NLDrnoh/qyZYoT4bC4nGSZwRhN8CLEAXNf2zEuqZFkqnVLbmJeUPs/730YElKy3FXEnPzk/1/kn28vCHzshnwOqVYCeyq4MGKJOGjOyMASQWmetu+oJ6rrVoaRuoAKka9flEbyrarMd6fGjhb9a+i7LBw5aT0RigORdVHDQizXJaH/o+v5LtMjKjUC6pQE+Y8oLEvON78cr0d9yhr0hHULwJpQ3NW1B4qVgzFPW2j1dSF5U3VGlimOjT37F5Hc3flWQ7ZP6g60kgvZFEb/qimjE2NDwAneGXZ9MsGRj7Zf1OjpTUPdBA3iYXHvFIK0iNbIRaj6b7zGJ4ua5rIOCPGodE1x3MsYOCdYLqf5g26I169CNFoCd7PGZG9LM8Qto4/SVZsM2ekZhzFrQSq7HUKxp/eb8Dl2x0="
    on_success: always
