language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
    - exe_extended_name: itkTensorFlow_${TRAVIS_BRANCH}_${TRAVIS_OS_NAME}
    - secure: ${GH_PERSONAL_ACCESS_TOKEN}

install:
  # download ITK
  - cd ${TRAVIS_BUILD_DIR}
  - cd ..
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      curl -L -O https://www.dropbox.com/s/zi7wfc9qev2529d/ITK413_osx_install.zip;
      unzip -a -q ITK413_osx_install.zip;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      curl -L -O https://www.dropbox.com/s/w35r9k376gg1cc3/ITK413_linux_install.zip;
      unzip -a -q ITK413_linux_install.zip;
    fi
  - cd ${TRAVIS_BUILD_DIR}

script:
  - mkdir bin
  - cd bin
  - cmake .. -DITK_DIR_HINTS="../ITK_install" -DCMAKE_INSTALL_PREFIX=install
  - cmake --build bin --config RELEASE --target itkTensorFlowTests
  - cd tests
  - ./itkTensorFlowTests
  - cd ${TRAVIS_BUILD_DIR}/bin
  - cmake --build bin --config RELEASE --target install

before_deploy:
  - cd ${TRAVIS_BUILD_DIR}/bin/install
  - zip -r ${exe_extended_name}.zip *
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir deployment
  - cp ${TRAVIS_BUILD_DIR}/bin/install/${exe_extended_name}.zip ${TRAVIS_BUILD_DIR}/deployment/${exe_extended_name}.zip
  - ls ${TRAVIS_BUILD_DIR}
  - ls ${TRAVIS_BUILD_DIR}/deployment

deploy:
  provider: releases # GitHub
  api_key:
    secure: ${GH_PERSONAL_ACCESS_TOKEN}
  file_glob: ON # to use wildcards
  file: deployment/*
  skip_cleanup: ON
  on:
    tags: ON
    condition: ${CXX} == "g++" # I guess I have to pick one compiler
